name: freeflownation.org
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on freeflownation.org
      uses: appleboy/ssh-action@master
      with:
        host: freeflownation.org
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 34022
        script: |
          cd websites/www_freeflownation/
          git log -1
          git restore .
          git pull
