name: freeflownation
on: 
  push:
    branch: [ development ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www.freeflownation.org
      uses: appleboy/ssh-action@master
      with:
        host: freeflownation.org
        username: ${{ secrets.TF_USER }}
        key: ${{ secrets.TF_SECRET }}
        port: ${{ secrets.TF_PORT }}
        script: |
          cd ~/websites/www_freeflownation
          git log -1
          git pull
